"""renamed leave table to leaves

Revision ID: 6889b81891cb
Revises: 5185c0d09bca
Create Date: 2024-04-17 22:38:30.536572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6889b81891cb'
down_revision = '5185c0d09bca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('leave', 'leaves')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('leaves', 'leave')
    # ### end Alembic commands ###
 