services:
  - type: web
    name: hr-hub-backend
    env: python
    region: oregon
    buildCommand: "pip install -r ../requirements.txt"
    startCommand: "cd app && flask run --host=0.0.0.0 --port=$PORT"
    pythonVersion: 3.11 
    envVars:
      - key: FLASK_APP
        value: app.py  
      - key: FLASK_ENV
        value: production
